# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'cucumber', '~> 8.0'

gem 'rake', '~> 13.0'

gem 'chutney', '~> 3.2'

gem 'rubocop', '~> 1.31'

gem 'pry', '~> 0.14.1'

gem 'rspec', '~> 3.11'

gem "logger", "~> 1.5"
